apply plugin: 'com.android.library'
apply from: '../build-system/dependencies.gradle'

android {

    defaultConfig {
        minSdkVersion emaVersioning.minSdk
        compileSdkVersion emaVersioning.compileSdk
        targetSdkVersion emaVersioning.targetSdk
        testInstrumentationRunner emaVersioning.testRunner

    }

    buildTypes {
        debug {
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = emaVersioning.javaVersion
        targetCompatibility = emaVersioning.javaVersion
    }

    kotlin {
        compilerOptions {
            jvmTarget = emaVersioning.kotlinJvmTarget
        }
    }
    namespace emaVersioning.namespaceTestingAndroid

}

dependencies {
    implementation project(":ema-android")
    implementation project(":ema-testing-core")

    //androidTest
    implementation emaTestingDependencies.core
    implementation emaTestingDependencies.coreKotlin
    implementation emaTestingDependencies.espresso
}
