apply plugin: 'kotlin'
apply from: '../build-system/dependencies.gradle'

dependencies {
    api project(":ema-core")
    api emaTestingDependencies.junit
    api emaTestingDependencies.junitKotlin
    api emaTestingDependencies.rules
    api emaTestingDependencies.mockito
    api emaTestingDependencies.coroutines
}
