plugins {
    alias(libs.plugins.kotlin.jvm)
}

java {
    sourceCompatibility = rootProject.emaVersioning.javaVersion
    targetCompatibility = rootProject.emaVersioning.javaVersion
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(rootProject.emaVersioning.kotlinJvmTarget)
    }
}

dependencies {
    api project(":ema-core")
    api libs.junit
    api libs.mockito.core
    api libs.kotlinx.coroutines.test
}
