// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply from: 'build-system/dependencies.gradle'

buildscript {
    apply from: 'build-system/dependencies.gradle'
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:${emaVersioning.agpVersion}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${emaVersioning.kotlinVersion}"
        classpath "org.jetbrains.kotlin:kotlin-serialization:${emaVersioning.kotlinVersion}"
    }
}
