rootProject.ext {

    emaLibraries = [
            emaAndroid       : ':ema-android',
            emaAndroidCompose: ':ema-android-compose',
            emaCore          : ':ema-core',
            emaTestingCore   : ':ema-testing-core',
            emaTestingAndroid: ':ema-testing-android',
    ]
}
