plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
    id 'maven-publish'
}

android {
    compileSdk = rootProject.emaVersioning.compileSdk

    defaultConfig {
        minSdk = rootProject.emaVersioning.minSdk
        targetSdk = rootProject.emaVersioning.targetSdk

        testInstrumentationRunner = rootProject.emaVersioning.testRunner

    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = rootProject.emaVersioning.javaVersion
        targetCompatibility = rootProject.emaVersioning.javaVersion
    }

    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(rootProject.emaVersioning.kotlinJvmTarget)
            optIn.add("com.carmabs.ema.core.EmaInternalApi")
        }
    }

    packaging {
        resources {
            pickFirsts += rootProject.emaVersioning.resourceExclusions
        }
    }


    buildFeatures {
        compose = true
    }

    publishing {
        singleVariant("release")
    }

    namespace = rootProject.emaVersioning.namespaceCompose
}

dependencies {
    implementation project(path: ':ema-android')
    implementation libs.kotlin.reflect

    api platform(libs.androidx.compose.bom)
    api libs.androidx.compose.ui
    api libs.androidx.compose.material.ripple
    api libs.androidx.compose.ui.tooling
    api libs.androidx.compose.ui.tooling.preview
    api libs.androidx.activity.compose
    api libs.androidx.lifecycle.runtime.compose
    api libs.androidx.lifecycle.viewmodel.compose
    api libs.androidx.navigation.compose

}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = rootProject.emaVersioning.groupId
                artifactId = rootProject.emaVersioning.artifactComposeId
                version = rootProject.emaVersioning.versionName
            }
        }
    }
}
