package com.carmabs.ema.android.configuration

import com.carmabs.ema.core.model.EmaMethodNameResolver

/**
 * Resolves the name of the method that launched a sideEffect from the name of the class generated by the
 * compiler for its lambda, for example `LoginViewModel$doLogin$1` → `doLogin`.
 *
 * @author <a href=“mailto:apps.carmabs@gmail.com”>Carlos Mateo Benito</a>
 */
object EmaAndroidMethodNameResolver : EmaMethodNameResolver {

    private const val DELIMITER = "$"

    override fun resolve(container: Any, action: Any): String {
        val methodName = action::class.java.name
            .substringAfter(container::class.java.name)
            .substringBeforeLast(DELIMITER, "")
            .substringAfter(DELIMITER)
        return methodName.ifEmpty { EmaMethodNameResolver.Default.resolve(container, action) }
    }
}
