apply from: '../build-system/dependencies.gradle'

buildscript {
    apply from: '../build-system/dependencies.gradle'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:${emaVersioning.agpVersion}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${emaVersioning.kotlinVersion}"
    }
}

apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {

    defaultConfig {
        compileSdkVersion emaVersioning.compileSdk
        minSdkVersion emaVersioning.minSdk
        targetSdk emaVersioning.targetSdk

        testInstrumentationRunner emaVersioning.testRunner

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = emaVersioning.javaVersion
        targetCompatibility = emaVersioning.javaVersion
    }

    kotlin {
        compilerOptions {
            jvmTarget = emaVersioning.kotlinJvmTarget
        }
    }

    packagingOptions {
        resources {
            pickFirsts += emaVersioning.resourceExclusions
        }
    }


    buildFeatures {
        viewBinding true
    }

    publishing {
        singleVariant("release")
    }

    namespace emaVersioning.namespaceAndroid
}

dependencies {

    implementation emaAndroidDependencies.reflection
    implementation emaAndroidDependencies.gson
    // Java language implementation
    // Kotlin
    api emaAndroidDependencies.fragment
    api emaAndroidDependencies.koin


    //Navigation
    api emaAndroidDependencies.navigationFragment
    api emaAndroidDependencies.navigationUI

    //Architecture components
    api emaAndroidDependencies.lifecycle
    api emaAndroidDependencies.lifecycleKtExtension
    //UI
    api emaAndroidDependencies.constraint
    api emaAndroidDependencies.material

    api project(path: ':ema-core')
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = emaVersioning.groupId
                artifactId = emaVersioning.artifactAndroidId
                version = emaVersioning.versionName
            }
        }
    }
}
