plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    id 'maven-publish'
}

java {
    sourceCompatibility = rootProject.emaVersioning.javaVersion
    targetCompatibility = rootProject.emaVersioning.javaVersion
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(rootProject.emaVersioning.kotlinJvmTarget)
    }
}

dependencies {
    api libs.kotlin.stdlib
    api libs.kotlinx.coroutines.android
    api libs.kotlinx.serialization.json
    implementation libs.kotlin.reflect
    implementation libs.androidx.annotation

    testImplementation libs.junit
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components["java"]
                groupId = rootProject.emaVersioning.groupId
                artifactId = rootProject.emaVersioning.artifactCoreId
                version = rootProject.emaVersioning.versionName
            }
        }
    }
}
