plugins {
    alias(libs.plugins.android.library)
    id 'maven-publish'
}

android {
    compileSdk = rootProject.emaVersioning.compileSdk

    defaultConfig {
        minSdk = rootProject.emaVersioning.minSdk
        targetSdk = rootProject.emaVersioning.targetSdk

        testInstrumentationRunner = rootProject.emaVersioning.testRunner

    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = rootProject.emaVersioning.javaVersion
        targetCompatibility = rootProject.emaVersioning.javaVersion
    }

    kotlin {
        compilerOptions {
            jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget(rootProject.emaVersioning.kotlinJvmTarget)
            optIn.add("com.carmabs.ema.core.EmaInternalApi")
        }
    }

    packaging {
        resources {
            pickFirsts += rootProject.emaVersioning.resourceExclusions
        }
    }


    buildFeatures {
        viewBinding = true
    }

    publishing {
        singleVariant("release")
    }

    namespace = rootProject.emaVersioning.namespaceAndroidView
}

dependencies {

    api project(path: ':ema-android')

    implementation libs.gson

    // Fragments and navigation
    api libs.androidx.fragment.ktx
    api libs.androidx.navigation.fragment.ktx
    api libs.androidx.navigation.ui.ktx

    //UI
    api libs.androidx.constraintlayout
    api libs.material
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = rootProject.emaVersioning.groupId
                artifactId = rootProject.emaVersioning.artifactAndroidViewId
                version = rootProject.emaVersioning.versionName
            }
        }
    }
}
